import Head from "next/head";

function SEO() {
  return (
    <div>
      <Head>
        <title>Boreal Clinica Dental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.svg" />
      </Head>
    </div>
  );
}

export default SEO;
