import React from "react";
import DinamicPage from "../components/DinamicPage";
import Head from "next/head";

export default function implenates() {
  return (
    <>
      <Head>
        <title>Implantes Dentales - Boreal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <DinamicPage
        title="Implantes Dentales y Rehabilitacion Oral"
        subtitle="Recupera y luce esa estupenda sonrisa que algún dia tuviste."
      />
    </>
  );
}
