import React from "react";
import DinamicPage from "../components/DinamicPage";
import Head from "next/head";

export default function implenates() {
  return (
    <>
      <Head>
        <title>Dise&ntilde;o de sonrisa - Boreal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <DinamicPage
        title="Dise&ntilde;o de sonrisa"
        subtitle="Hacemos una mejor sonrisa para ti"
      />
    </>
  );
}
